In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import numpy as np

In [5]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [6]:
myElection_Donations = pd.read_csv("/anvil/projects/tdm/data/election/itcont1980.txt", header=None, sep='|') #header=None: Indicates that the file does not contain column headers. Without this, Pandas will assume the first row contains column names.
#sep='|': Specifies that the columns in the file are separated by a pipe (|) character.

In [7]:
# Step 3 - Assign Column Names

In [8]:
myElection_Donations.columns = ["CMTE_ID", "AMNDT_IND", "RPT_TP", "TRANSACTION_PGI", "IMAGE_NUM", "TRANSACTION_TP", "ENTITY_TP", "NAME", "CITY", "STATE", "ZIP_CODE", "EMPLOYER", "OCCUPATION", "TRANSACTION_DT", "TRANSACTION_AMT", "OTHER_ID", "TRAN_ID", "FILE_NUM", "MEMO_CD", "MEMO_TEXT", "SUB_ID"]
#myElection_Donations.columns: Replaces the default column names (e.g., integers) with meaningful names based on the dataset's structure

In [9]:
# Step 4 - # Display first 5 rows of data from the election donations data frame(similar to Top 5 in sql) - click run

In [10]:
myElection_Donations.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,10031979.0,400,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1500,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,300,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1000,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,3201979.0,200,NaN,NaN,NaN,NaN,NaN,3061920110000383914

In [11]:
#Counting the value that appears in the "STATE" column the most times

In [17]:
myElection_Donations['STATE'].value_counts(dropna = False)

STATE
CA    37069
TX    34862
NY    25669
IL    15895
FL    15576
      ...
01        3
AS        2
TU        1
BE        1
EL        1
Name: count, Length: 62, dtype: int64

In [13]:
#Counting the value that appears in the "NAME" column the most times

In [14]:
myElection_Donations['NAME'].value_counts(dropna = False)

NAME
AMERICAN MEDICAL POLITICAL ACTION COMMITTEE    769
AMERICAN DENTAL POLITICAL ACTION COMMITTEE      96
REPP, WARD W                                    89
DEMOCRATIC CONGRESSIONAL DINNER COMMITTEE       65
WILLIAMS, J D                                   64
                                              ...
MOYER, MONROE M                                  1
NARVID, MICHAEL J                                1
NORMAN, A E                                      1
ASTON, ARTHUR                                    1
STUART, HAROLD MRS                               1
Name: count, Length: 217646, dtype: int64

In [15]:
#Display the myElection_Donations dataframe

In [16]:
myElection_Donations

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,10031979.0,400,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1500,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,300,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1000,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,3201979.0,200,NaN,NaN,NaN,NaN,NaN,3061920110000383914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308691,C99003063,N,YE,NaN,81031902915,15,NaN,"PLEMAN, THOMAS J",WESTLAKE ISLAND,CA,...,STUDENT,NaN,10171980.0,500,NaN,NaN,NaN,NaN,NaN,3061920110000777082
308692,C99003063,N,YE,NaN,81031902915,15,NaN,"SHEINBAUM, STANLEY",LOS ANGELES,CA,...,ECONOMIST,NaN,10161980.0,500,NaN,NaN,NaN,NaN,NaN,3061920110000777083
308693,C00144170,N,YE,NaN,83032835154,15,NaN,"PHILLIPS, LEONARD",SHREVEPORT,LA,...,SKLAR & PHILLIPS OIL CO,NaN,10091981.0,500,NaN,NaN,NaN,NaN,NaN,3061920110000579479
308694,C00144170,N,YE,NaN,83032835154,15,NaN,"PHILLIPS, BETTY S",SHREVEPORT,LA,...,HOUSEWIFE,NaN,10091981.0,500,NaN,NaN,NaN,NaN,NaN,3061920110000579480
308695,C00109637,N,YE,NaN,81020013947,15,NaN,"STUART, HAROLD MRS",TULSA,OK,...,HOUSEWIFE,NaN,12091980.0,500,NaN,NaN,NaN,NaN,NaN,3061920110000674036