In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [4]:
myPassing_Rec = pd.read_csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv")

In [7]:
# Step 4 - # Display first 5 rows of data from the Death Records data frame(similar to Top 5 in sql) - click run

In [8]:
myPassing_Rec.head()

,Id,ResidentStatus,Education1989Revision,Education2003Revision,EducationReportingFlag,MonthOfDeath,Sex,AgeType,Age,AgeSubstitutionFlag,...,CauseRecode39,NumberOfEntityAxisConditions,NumberOfRecordAxisConditions,Race,BridgedRaceFlag,RaceImputationFlag,RaceRecode3,RaceRecode5,HispanicOrigin,HispanicOriginRaceRecode
0,1,1,0,2,1,1,M,1,87,0,...,24,1,1,1,0,0,1,1,100,6
1,2,1,0,2,1,1,M,1,58,0,...,21,3,3,1,0,0,1,1,100,6
2,3,1,0,7,1,1,F,1,75,0,...,28,2,2,1,0,0,1,1,100,6
3,4,1,0,6,1,1,M,1,74,0,...,22,3,3,1,0,0,1,1,100,6
4,5,1,0,3,1,1,M,1,64,0,...,21,1,1,1,0,0,1,1,100,6

In [8]:
#Set display option to show all columns - Configures Pandas to display all columns of a DataFrame when printed or 
#displayed in an interactive environment (e.g., Jupyter Notebook)

In [9]:
pd.set_option('display.max_columns',None)
#pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myPassing_Rec

,Id,ResidentStatus,Education1989Revision,Education2003Revision,EducationReportingFlag,MonthOfDeath,Sex,AgeType,Age,AgeSubstitutionFlag,AgeRecode52,AgeRecode27,AgeRecode12,InfantAgeRecode22,PlaceOfDeathAndDecedentsStatus,MaritalStatus,DayOfWeekOfDeath,CurrentDataYear,InjuryAtWork,MannerOfDeath,MethodOfDisposition,Autopsy,ActivityCode,PlaceOfInjury,Icd10Code,CauseRecode358,CauseRecode113,InfantCauseRecode130,CauseRecode39,NumberOfEntityAxisConditions,NumberOfRecordAxisConditions,Race,BridgedRaceFlag,RaceImputationFlag,RaceRecode3,RaceRecode5,HispanicOrigin,HispanicOriginRaceRecode
0,1,1,0,2,1,1,M,1,87,0,43,23,11,0,4,M,4,2014,U,7,C,N,99,99,I64,238,70,0,24,1,1,1,0,0,1,1,100,6
1,2,1,0,2,1,1,M,1,58,0,37,17,8,0,4,D,3,2014,U,7,C,N,99,99,I250,214,62,0,21,3,3,1,0,0,1,1,100,6
2,3,1,0,7,1,1,F,1,75,0,41,21,10,0,4,W,2,2014,U,7,C,N,99,99,J449,267,86,0,28,2,2,1,0,0,1,1,100,6
3,4,1,0,6,1,1,M,1,74,0,40,20,9,0,6,D,1,2014,U,7,C,N,99,99,I48,228,68,0,22,3,3,1,0,0,1,1,100,6
4,5,1,0,3,1,1,M,1,64,0,38,18,8,0,4,D,2,2014,U,7,C,N,99,99,I250,214,62,0,21,1,1,1,0,0,1,1,100,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2631166,2631167,3,0,6,1,12,M,1,84,0,42,22,10,0,6,S,2,2014,U,7,B,N,99,99,I119,207,56,0,20,4,4,1,0,0,1,1,100,6
2631167,2631168,3,0,9,1,12,F,1,74,0,40,20,9,0,6,S,7,2014,U,7,B,N,99,99,I251,215,63,0,21,2,2,1,0,1,1,1,998,9
2631168,2631169,3,0,1,1,12,M,6,7,0,1,1,1,1,1,S,4,2014,U,7,B,Y,99,99,P072,358,108,89,33,2,1,1,0,1,1,1,998,9
2631169,2631170,4,0,9,1,2,M,1,49,0,35,15,7,0,1,U,1,2014,U,7,O,N,99,99,I250,214,62,0,21,5,5,2,0,0,3,2,998,9
2631170,2631171,3,0,1,1,5,M,6,39,0,1,1,1,1,1,S,2,2014,U,7,O,N,99,99,P291,364,108,117,33,2,1,2,0,0,3,2,100,7

In [10]:
#Group by 'Sex' and calculate average age - Groups the myPassing_Rec DataFrame by sex, 
#calculates the average age at passing for each sex, and resets the index to return a clean DataFrame

In [11]:
pd.set_option('display.max_rows',None) # - pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myPassing_Rec.groupby('Sex')['Age'].mean().reset_index(name='Avg_Age')

  Sex    Avg_Age
0   F  76.676685
1   M  70.227858