In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [11]:
import pandas as pd

In [12]:
import matplotlib.pyplot as plt

In [13]:
import numpy as np

In [14]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [15]:
myElection_Donations = pd.read_csv("/anvil/projects/tdm/data/election/itcont1980.txt", header=None, sep='|') #header=None: Indicates that the file does not contain column headers. Without this, Pandas will assume the first row contains column names.
#sep='|': Specifies that the columns in the file are separated by a pipe (|) character.

In [16]:
# Step 3 - Assign Column Names

In [17]:
myElection_Donations.columns = ["CMTE_ID", "AMNDT_IND", "RPT_TP", "TRANSACTION_PGI", "IMAGE_NUM", "TRANSACTION_TP", "ENTITY_TP", "NAME", "CITY", "STATE", "ZIP_CODE", "EMPLOYER", "OCCUPATION", "TRANSACTION_DT", "TRANSACTION_AMT", "OTHER_ID", "TRAN_ID", "FILE_NUM", "MEMO_CD", "MEMO_TEXT", "SUB_ID"]
#myElection_Donations.columns: Replaces the default column names (e.g., integers) with meaningful names based on the dataset's structure

In [18]:
# Step 4 - # Display first 5 rows of data from the election donations data frame(similar to Top 5 in sql) - click run

In [19]:
myElection_Donations.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,10031979.0,400,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1500,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,300,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1000,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,3201979.0,200,NaN,NaN,NaN,NaN,NaN,3061920110000383914

In [20]:
#Combines the CITY and STATE columns into a single string in the format CITY, STATE
#Group the data by this combined string to aggregate donation amounts (TRANSACTION_AMT) for each city-state pair
#The dropna=False ensures that rows with missing values in either column are not excluded from the grouping process
#Calclates the donation amounts (TRANSACTION_AMT) for each group (city-state pair) by summing them
#Rename the calculated column (TRANSACTION_AMT) to DONATION_AMT for clarity
#Select the last 21 rows of the grouped and aggregated DataFrame
#Sort the resulting DataFrame by the DONATION_AMT column in descending order (ascending=False), so cities/states with the highest total donations appear at the top.

In [22]:
myElection_Donations.groupby(myElection_Donations['CITY'] + ', ' + myElection_Donations['STATE'], dropna = False)['TRANSACTION_AMT'].sum().reset_index(name='DONATION_AMT').tail(21).sort_values(by='DONATION_AMT',ascending=False)

                  index  DONATION_AMT
19521               NaN      18092711
19512    ZIONSVILLE, IN         26604
19506   ZEPHYR COVE, NV          8449
19510        ZILLAH, WA          6370
19509   ZEPHYRHILLS, FL          6020
19514     ZIONVILLE, IN          3650
19504        ZENITH, WA          2990
19501       ZEELAND, MI          2455
19513    ZIONSVILLE, PA          1250
19515    ZIONVILLLE, IN          1000
19507  ZEPHYR HILLS, FL           800
19508   ZEPHYRHILIS, FL           725
19518        ZWOLLE, LA           700
19502        ZEINTH, WA           500
19503      ZELLWOOD, FL           500
19517      ZUMBROTA, MN           500
19519  [AULS VALLEY, OK           500
19520     [NCHORAGE, AK           500
19511          ZION, IL           500
19505       ZEPHYER, TX           250
19516    ZRONSVILLE, IN           250