In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [5]:
myBeer_Review = pd.read_csv("/anvil/projects/tdm/data/beer/reviews_sample.csv")

In [6]:
# Step 3 - # Display first 5 rows of data from the Beer review data frame(similar to Top 5 in sql) - click run

In [7]:
myBeer_Review.head()

,beer_id,username,date,text,look,smell,taste,feel,overall,score
0,271781,bluejacket74,2017-03-17,"750 ml bottle, 2016 vintage, bottle #304 of...",4.00,4.00,4.00,4.25,4.00,4.03
1,125646,_dirty_,2017-12-21,,4.50,4.50,4.50,4.50,4.50,4.50
2,125646,CJDUBYA,2017-12-21,,4.75,4.75,4.75,4.75,4.75,4.75
3,125646,GratefulBeerGuy,2017-12-20,0% 16 oz can. Funny story: As I finally wal...,4.75,4.75,4.50,4.50,4.50,4.58
4,125646,LukeGude,2017-12-20,Classic TH NEIPA. Overflowing head and bouq...,4.25,4.50,4.25,4.25,4.25,4.31

In [8]:
#Set display option to show all columns - Configures Pandas to display all columns of a DataFrame when printed or 
#displayed in an interactive environment (e.g., Jupyter Notebook)

In [9]:
pd.set_option('display.max_columns',None)
#pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myBeer_Review

,beer_id,username,date,text,look,smell,taste,feel,overall,score
0,271781,bluejacket74,2017-03-17,"750 ml bottle, 2016 vintage, bottle #304 of...",4.00,4.00,4.00,4.25,4.00,4.03
1,125646,_dirty_,2017-12-21,,4.50,4.50,4.50,4.50,4.50,4.50
2,125646,CJDUBYA,2017-12-21,,4.75,4.75,4.75,4.75,4.75,4.75
3,125646,GratefulBeerGuy,2017-12-20,0% 16 oz can. Funny story: As I finally wal...,4.75,4.75,4.50,4.50,4.50,4.58
4,125646,LukeGude,2017-12-20,Classic TH NEIPA. Overflowing head and bouq...,4.25,4.50,4.25,4.25,4.25,4.31
...,...,...,...,...,...,...,...,...,...,...
999994,52633,KTCamm,2010-03-12,Poured from a 12 oz bottle into a pint glas...,3.50,3.00,3.00,3.00,3.50,3.13
999995,52633,cjgator3,2010-03-11,12oz bottle A- Pours a hazy golden orangish...,4.00,3.00,3.50,3.50,3.50,3.41
999996,92,EersandBeers,2017-08-22,,4.00,4.00,4.00,4.00,3.50,3.90
999997,92,wisegreensoul,2015-06-02,,4.00,3.75,4.00,4.25,4.00,3.97
999998,92,hoppy91,2014-11-07,,NaN,NaN,NaN,NaN,NaN,4.00

In [10]:
#Group by 'date' and calculate mean "Avg_Score - Groups the beer reviews DataFrame by date, calculates the mean (Avg_Score) for the 3 dates with a score of 5,
# sort the values, call the last 3 rows of data, and resets the index and renames the calculated column as Avg_Score

In [22]:
pd.set_option('display.max_rows',None)
myAvgBeer_Review=myBeer_Review.groupby('date')['score'].mean().sort_values().reset_index(name='Avg_Score')
#Groups the data by the date column (representing date)
#Averages the beer review scores to calculate (mean) the Avg_Score column for each date group to calculate Avg_Score by date
#Sorts the calculated avg score values in ascending order
#Selects the top 3 date with the highest Avg_Review that equals 5 by taking the last 3 rows of the sorted data
#Resets the index and renames the calculated column as Avg_Spend

In [23]:
# Displays the resulting DataFrame (myAvgBeer_Review) containing the top 3 dates with there average calculated score values.

In [24]:
myAvgBeer_Review

            date  Avg_Score
0     2002-02-13   1.000000
1     2002-05-10   1.900000
2     2001-10-24   2.000000
3     2001-12-23   2.000000
4     2001-04-25   2.080000
5     2002-10-22   2.353333
6     2002-08-18   2.422500
7     2001-08-17   2.530000
8     2001-09-25   2.560000
9     2002-05-13   2.575000
10    2002-08-09   2.593333
11    2001-10-18   2.600000
12    2001-10-16   2.600000
13    2002-02-28   2.700000
14    2002-04-08   2.735000
15    2002-09-11   2.760000
16    2002-02-15   2.760000
17    1998-09-06   2.770000
18    2002-08-16   2.805000
19    1998-04-16   2.850000
20    1998-02-19   2.855000
21    2001-12-14   2.860000
22    2003-07-01   2.900000
23    2002-03-10   2.910000
24    2002-02-24   2.930000
25    2004-08-18   2.970000
26    2002-08-24   2.975000
27    2002-06-22   3.040000
28    2006-03-10   3.053000
29    2001-06-24   3.080000
30    1998-07-07   3.100000
31    2004-10-06   3.106000
32    2003-04-19   3.112500
33    2002-02-18   3.120000
34    2002-05-26   3.136667
35    2002-07-20   3.140000
36    2004-07-14   3.162857
37    2002-08-13   3.166667
38    2007-05-03   3.169091
39    2003-12-31   3.187778
40    2002-10-26   3.190000
41    2005-01-19   3.191250
42    1999-02-09   3.195000
43    2003-08-03   3.201000
44    2001-10-20   3.210000
45    2002-03-02   3.230000
46    2002-06-15   3.231667
47    2003-07-24   3.238333
48    2007-07-31   3.247500
49    2005-11-18   3.250714
50    2002-03-23   3.260000
51    2006-05-14   3.266923
52    2004-03-14   3.271000
53    2002-08-19   3.280000
54    2005-07-24   3.282727
55    2003-06-04   3.286000
56    2002-11-19   3.295000
57    2002-10-16   3.300000
58    2006-06-09   3.304545
59    2002-09-06   3.305000
60    2006-08-08   3.306250
61    2002-07-24   3.315000
62    2002-03-25   3.320000
63    2003-09-29   3.328000
64    2002-04-05   3.336000
65    2004-10-01   3.343636
66    2005-04-08   3.347143
67    2006-11-28   3.347368
68    2002-02-03   3.350000
69    2002-09-04   3.350000
70    2004-11-13   3.350000
71    2007-06-29   3.356842
72    2004-01-20   3.358571
73    2003-01-27   3.360000
74    2006-09-12   3.362632
75    2003-08-17   3.365000
76    2004-08-02   3.365714
77    2002-11-10   3.375000
78    2003-08-30   3.375833
79    2007-05-09   3.376250
80    2003-09-12   3.377000
81    2004-04-02   3.380000
82    2007-11-18   3.380385
83    2002-12-20   3.385000
84    2004-03-01   3.387500
85    2004-07-04   3.388000
86    2003-07-20   3.392000
87    2004-07-10   3.392857
88    2003-07-29   3.395000
89    2007-09-12   3.396667
90    2000-12-30   3.400000
91    2002-10-12   3.400000
92    2001-07-11   3.400000
93    1998-05-25   3.400000
94    2001-11-30   3.400000
95    2003-04-10   3.403333
96    2005-02-25   3.406667
97    2003-07-17   3.410000
98    2001-12-20   3.410000
99    2003-12-06   3.410833
100   2004-10-05   3.411111
101   2006-04-17   3.413000
102   2002-08-07   3.413333
103   2007-03-30   3.416364
104   2004-12-15   3.418000
105   2004-03-17   3.420000
106   2002-06-29   3.420000
107   2003-08-23   3.421111
108   2002-10-23   3.423333
109   2007-08-11   3.425882
110   2002-11-03   3.426000
111   2004-11-03   3.428182
112   2005-08-02   3.428889
113   2007-06-11   3.431538
114   2007-06-27   3.435714
115   2003-06-26   3.436250
116   2005-06-13   3.439000
117   2005-09-28   3.439000
118   2003-03-16   3.440000
119   2002-04-22   3.440000
120   2002-10-03   3.442000
121   2003-03-21   3.442500
122   2005-05-04   3.442500
123   2003-12-30   3.442727
124   2004-06-29   3.442857
125   2005-06-01   3.442857
126   2005-05-27   3.443077
127   2002-09-24   3.443333
128   2002-08-23   3.444000
129   2004-06-13   3.445385
130   2002-11-28   3.446667
131   2005-04-29   3.447143
132   2002-10-11   3.448333
133   2004-12-17   3.449091
134   2004-03-18   3.450000
135   1998-02-21   3.450000
136   1998-03-09   3.450000
137   2007-08-10   3.453000
138   2004-02-14   3.453333
139   2004-04-01   3.453636
140   2004-03-22   3.454545
141   2003-07-27   3.456667
142   2004-11-20   3.456667
143   2002-08-01   3.457500
144   2003-06-14   3.458000
145   2002-04-19   3.458000
146   2007-04-24   3.458235
147   2005-07-21   3.460000
148   2006-03-20   3.460000
149   2003-08-09   3.461111
150   2002-06-16   3.462500
151   2007-04-23   3.463333
152   2007-12-06   3.463333
153   2003-01-07   3.468333
154   2003-09-21   3.470000
155   2005-05-16   3.471176
156   2004-12-20   3.471250
157   2007-09-04   3.471667
158   2003-03-28   3.472222
159   2002-08-02   3.473333
160   2002-11-05   3.473333
161   2003-11-09   3.475000
162   2007-07-02   3.477368
163   2001-10-03   3.480000
164   2005-02-13   3.480000
165   2001-10-31   3.480000
166   2002-06-26   3.480000
167   2005-07-15   3.484545
168   2002-09-15   3.485714
169   2006-05-29   3.485789
170   2004-11-27   3.486667
171   2002-04-13   3.486667
172   2005-02-18   3.487500
173   2004-11-10   3.488333
174   2004-06-22   3.489167
175   2004-03-21   3.491667
176   2005-09-12   3.492308
177   2007-01-17   3.492667
178   2007-02-22   3.494286
179   2003-06-25   3.495000
180   2003-04-08   3.495833
181   2005-08-29   3.496923
182   2007-08-09   3.497692
183   2008-10-26   3.498065
184   2002-10-13   3.498333
185   2003-09-03   3.498462
186   2007-08-06   3.498571
187   2004-04-24   3.498750
188   1999-10-05   3.500000
189   2002-08-05   3.500000
190   1999-10-03   3.500000
191   2003-06-23   3.502500
192   2005-02-24   3.502500
193   2003-10-30   3.504000
194   2005-12-05   3.504000
195   2005-08-22   3.505000
196   2007-02-21   3.505333
197   2007-01-01   3.505385
198   2002-05-23   3.506667
199   2004-07-05   3.507000
200   2003-08-18   3.507500
201   2002-06-19   3.507500
202   2005-09-05   3.507500
203   2004-10-12   3.507500
204   2003-10-24   3.507778
205   2005-07-13   3.508182
206   2006-08-07   3.510370
207   2002-10-08   3.511667
208   2006-06-30   3.512000
209   2006-07-31   3.512667
210   2003-07-11   3.513333
211   2005-05-08   3.515000
212   2003-08-27   3.516429
213   2004-09-17   3.516875
214   2006-03-23   3.517500
215   2006-10-22   3.517727
216   2004-10-23   3.520000
217   2003-12-04   3.521250
218   2002-07-29   3.521667
219   2002-08-10   3.522857
220   2004-11-06   3.523000
221   2003-10-27   3.523333
222   2005-08-08   3.524286
223   2008-03-20   3.525000
224   2007-04-12   3.525385
225   2005-04-12   3.525385
226   2006-08-18   3.525556
227   2003-03-02   3.526000
228   2002-03-28   3.526000
229   2001-10-26   3.526667
230   2002-06-04   3.528571
231   2008-07-12   3.529500
232   2003-03-01   3.530000
233   2005-04-25   3.531111
234   2003-07-21   3.532000
235   2002-12-01   3.533333
236   2004-12-18   3.533846
237   2004-05-23   3.534000
238   2004-09-01   3.534167
239   2005-05-23   3.535000
240   2006-12-08   3.535000
241   2007-09-08   3.536250
242   2002-08-06   3.536667
243   2004-09-11   3.537000
244   2008-08-28   3.539231
245   2007-08-04   3.539412
246   2006-08-13   3.539565
247   2004-08-26   3.540000
248   2007-09-01   3.540000
249   2003-03-10   3.540000
250   2005-09-29   3.541000
251   2004-11-28   3.541429
252   2005-09-16   3.541429
253   2005-11-28   3.542000
254   2005-09-03   3.543000
255   2005-08-28   3.544167
256   2005-05-29   3.544286
257   2002-12-11   3.546000
258   2003-01-28   3.546000
259   2008-12-05   3.546800
260   2006-11-04   3.546818
261   2006-10-06   3.547143
262   2007-03-13   3.547143
263   2007-12-10   3.547778
264   2004-08-05   3.548000
265   2004-10-18   3.548750
266   2003-05-25   3.550000
267   2004-04-21   3.550000
268   2004-01-25   3.550000
269   2005-05-24   3.550000
270   2005-10-31   3.551176
271   2004-05-19   3.551250
272   2003-12-25   3.551429
273   2005-08-15   3.551818
274   2003-11-06   3.552000
275   2004-11-18   3.552000
276   2006-09-13   3.552500
277   2009-06-19   3.552778
278   2006-05-23   3.553333
279   2004-09-19   3.554286
280   2006-10-04   3.556154
281   2006-07-05   3.556250
282   2007-05-29   3.556923
283   2003-12-27   3.558571
284   2009-04-26   3.558696
285   2002-08-03   3.560000
286   2002-03-05   3.560000
287   2006-02-16   3.560000
288   2008-05-07   3.560714
289   2008-08-23   3.561951
290   2005-08-03   3.563077
291   2003-03-07   3.563333
292   2003-07-12   3.563750
293   2002-04-26   3.564000
294   2004-10-15   3.564286
295   2002-11-14   3.565000
296   2003-01-15   3.565000
297   2007-01-08   3.565833
298   2006-09-25   3.567500
299   2008-09-18   3.567826
300   2002-10-17   3.568182
301   2006-03-29   3.568182
302   2008-05-01   3.568235
303   2004-06-09   3.569167
304   2002-12-24   3.570000
305   2005-02-26   3.570000
306   2004-03-29   3.570000
307   2004-09-29   3.571111
308   2007-08-03   3.571429
309   2006-12-22   3.571538
310   2005-10-01   3.571667
311   2006-07-14   3.572667
312   2006-01-14   3.573077
313   2007-12-04   3.573333
314   2002-07-27   3.574000
315   2006-07-22   3.574615
316   2004-11-19   3.575000
317   2008-12-14   3.575476
318   2003-12-12   3.575556
319   2004-06-08   3.575714
320   2009-08-30   3.576098
321   2007-03-15   3.576471
322   2004-02-06   3.576471
323   2007-11-13   3.577143
324   2007-03-27   3.577222
325   2003-12-09   3.577273
326   2005-11-25   3.577857
327   2008-07-16   3.578571
328   2006-12-01   3.578750
329   2004-05-06   3.579231
330   2008-06-23   3.579444
331   2002-12-13   3.580000
332   2003-07-16   3.580000
333   2002-06-17   3.580000
334   2002-06-21   3.580000
335   2007-02-28   3.580769
336   2004-05-29   3.580833
337   2003-09-05   3.581111
338   2004-05-08   3.581111
339   2003-06-03   3.581667
340   2003-03-29   3.582000
341   2007-11-06   3.582143
342   2007-10-30   3.582143
343   2005-10-30   3.582308
344   2007-05-19   3.583125
345   2003-11-11   3.584000
346   2006-11-19   3.584444
347   2005-01-28   3.585000
348   2007-04-28   3.585000
349   2007-07-08   3.585789
350   2003-12-28   3.586000
351   2002-07-05   3.586000
352   2003-01-29   3.586667
353   2008-10-24   3.586800
354   2004-02-28   3.587143
355   2002-10-28   3.587143
356   2006-09-07   3.587500
357   2007-08-28   3.588182
358   2002-11-29   3.589000
359   2003-03-11   3.590000
360   2003-05-13   3.590000
361   2003-09-26   3.591250
362   2007-05-18   3.591667
363   2005-10-13   3.592500
364   2005-10-15   3.593333
365   2003-08-04   3.593750
366   2005-01-06   3.594444
367   2005-04-03   3.594615
368   2010-07-18   3.595000
369   2004-09-05   3.596875
370   2003-03-31   3.597273
371   2004-08-29   3.597500
372   2005-03-21   3.598000
373   2004-11-09   3.598333
374   2011-09-26   3.598358
375   2004-11-01   3.599167
376   2002-10-21   3.600000
377   2004-10-20   3.600000
378   2002-12-08   3.600000
379   2006-11-26   3.600000
380   2006-10-20   3.600556
381   2003-10-11   3.601667
382   2007-06-06   3.602500
383   2006-05-11   3.602500
384   2006-02-14   3.602778
385   2006-08-09   3.604000
386   2007-10-11   3.604091
387   2008-04-15   3.604211
388   2003-06-09   3.604545
389   2006-01-21   3.604737
390   2009-02-02   3.604783
391   2007-06-13   3.605000
392   2006-12-31   3.606000
393   2004-06-23   3.606000
394   2003-10-15   3.606667
395   2007-01-18   3.607857
396   2002-04-14   3.608000
397   2004-07-31   3.608000
398   2006-02-07   3.608462
399   2004-05-14   3.608571
400   2005-05-30   3.609286
401   2002-03-08   3.610000
402   2003-09-01   3.610000
403   1998-02-22   3.610000
404   2003-11-01   3.610000
405   2009-01-29   3.610800
406   2007-06-25   3.611176
407   2006-09-24   3.611500
408   2003-10-26   3.611818
409   2004-09-26   3.612222
410   2010-01-22   3.612619
411   2006-01-02   3.612667
412   2007-08-02   3.612667
413   2007-02-09   3.612941
414   2006-10-27   3.613077
415   2005-11-15   3.613333
416   2007-06-07   3.614000
417   2008-09-12   3.614091
418   2005-12-24   3.614286
419   2007-08-24   3.615000
420   2005-12-30   3.615625
421   2003-05-16   3.616000
422   2003-11-04   3.616667
423   2008-02-06   3.616667
424   2004-05-02   3.617143
425   2007-09-05   3.617500
426   2007-08-20   3.617647
427   2006-07-12   3.618125
428   2007-05-07   3.618333
429   2006-05-27   3.618889
430   2007-01-19   3.619167
431   2005-06-21   3.619375
432   2005-09-11   3.619375
433   2009-03-12   3.619643
434   1998-10-13   3.620000
435   2003-04-06   3.620000
436   2010-02-03   3.620278
437   2008-09-14   3.620455
438   2003-11-08   3.621765
439   2004-09-24   3.622000
440   2011-08-16   3.622113
441   2007-06-02   3.623529
442   2007-06-28   3.623889
443   2007-09-30   3.624000
444   2007-09-22   3.624375
445   2006-12-12   3.624545
446   2007-05-28   3.624706
447   2002-04-04   3.625000
448   2003-06-01   3.625000
449   2003-06-10   3.625000
450   2002-08-14   3.625714
451   2006-06-12   3.625714
452   2006-10-07   3.626364
453   2004-04-06   3.626429
454   2009-09-09   3.627317
455   2006-07-17   3.627333
456   2008-03-24   3.627895
457   2005-10-21   3.628000
458   2004-07-22   3.628000
459   2003-02-17   3.628000
460   2006-06-20   3.628571
461   2004-12-21   3.629167
462   2009-11-04   3.629545
463   2009-09-28   3.630000
464   2002-06-08   3.630000
465   1998-12-04   3.630000
466   2002-07-10   3.630000
467   2006-09-05   3.630000
468   2011-08-12   3.631127
469   2010-01-13   3.631176
470   2008-12-23   3.631667
471   2003-12-29   3.631818
472   2006-12-15   3.631818
473   2008-05-08   3.632609
474   2003-07-05   3.632667
475   2007-08-30   3.632778
476   2002-11-30   3.632857
477   2006-11-10   3.633077
478   2005-07-10   3.633333
479   2006-01-30   3.633913
480   2006-12-05   3.634167
481   2003-11-03   3.634167
482   2003-01-13   3.635000
483   2005-11-01   3.635455
484   2004-03-25   3.635714
485   2005-01-12   3.636000
486   2006-10-03   3.636111
487   2008-09-02   3.636207
488   2003-10-02   3.636667
489   2008-12-16   3.637021
490   2007-11-02   3.637222
491   2008-12-04   3.637407
492   2004-02-16   3.637692
493   2005-04-04   3.638571
494   2005-03-11   3.638571
495   2003-08-13   3.638889
496   2007-05-10   3.638947
497   2007-05-23   3.640000
498   2004-05-27   3.640000
499   2004-10-09   3.640000
500   2007-05-14   3.640000
501   2006-08-11   3.640667
502   2007-02-13   3.642222
503   2007-09-11   3.642308
504   2010-10-16   3.642615
505   2007-04-10   3.643000
506   2005-10-05   3.643077
507   2003-09-07   3.643636
508   2005-12-28   3.643846
509   2007-03-25   3.644091
510   2008-12-03   3.644194
511   2008-03-19   3.644815
512   2006-02-24   3.645882
513   2008-05-21   3.646111
514   2005-05-01   3.646250
515   2003-02-09   3.646364
516   2006-11-06   3.647059
517   2006-10-26   3.647143
518   2007-08-21   3.647222
519   2007-06-20   3.647273
520   2003-03-23   3.647778
521   2005-12-26   3.648750
522   2009-08-25   3.648966
523   2008-10-09   3.649048
524   2006-10-17   3.649231
525   2002-05-07   3.650000
526   2002-02-05   3.650000
527   2004-05-26   3.650000
528   2002-06-05   3.650000
529   2006-10-12   3.650000
530   2005-10-12   3.650000
531   2007-04-09   3.650526
532   2010-03-25   3.650741
533   2007-05-01   3.650909
534   2007-04-08   3.651053
535   2004-02-29   3.651176
536   2004-07-18   3.651667
537   2005-07-08   3.652222
538   2002-06-01   3.653333
539   2002-12-23   3.653333
540   2007-12-31   3.654848
541   2002-10-24   3.655000
542   2008-03-02   3.655200
543   2009-03-13   3.656000
544   2005-09-02   3.656429
545   2011-03-09   3.656543
546   2003-11-20   3.657500
547   2004-01-10   3.657647
548   2003-09-23   3.658182
549   2004-09-10   3.658333
550   2006-11-29   3.658824
551   2004-06-24   3.659231
552   2007-07-17   3.659286
553   2007-03-20   3.660000
554   2003-10-01   3.660000
555   2005-05-11   3.660000
556   2005-06-12   3.660000
557   2002-09-30   3.660000
558   2001-12-07   3.660000
559   2002-08-30   3.660000
560   2002-05-15   3.660000
561   2007-10-04   3.660000
562   2003-08-31   3.661111
563   2008-10-20   3.661481
564   2002-09-29   3.662500
565   2009-09-27   3.662553
566   2008-05-12   3.663000
567   2005-01-26   3.663333
568   2008-03-26   3.663448
569   2005-03-07   3.663636
570   2008-09-05   3.663793
571   2007-06-18   3.663846
572   2005-02-10   3.664000
573   2006-04-13   3.664444
574   2005-09-13   3.664545
575   2004-11-08   3.664545
576   2006-05-09   3.664762
577   2003-03-12   3.665000
578   2007-06-04   3.665000
579   2008-06-10   3.666087
580   2005-07-18   3.666111
581   2012-06-01   3.666165
582   2004-04-27   3.666250
583   2003-08-24   3.666250
584   2007-11-21   3.666667
585   2002-06-11   3.666667
586   2004-01-30   3.667143
587   2002-05-22   3.667500
588   2008-11-20   3.667500
589   2004-05-31   3.667778
590   2007-07-10   3.667778
591   2008-06-21   3.667895
592   2006-10-25   3.668000
593   2004-10-25   3.668333
594   2007-02-15   3.668571
595   2008-08-19   3.668710
596   2003-06-27   3.669000
597   2010-05-11   3.669773
598   2007-03-21   3.670000
599   2003-08-11   3.670000
600   2004-06-04   3.670000
601   1998-08-04   3.670000
602   2006-03-30   3.670800
603   2005-03-18   3.670909
604   2006-05-26   3.670909
605   2005-06-04   3.671429
606   2007-08-18   3.671875
607   2008-12-11   3.671935
608   2009-12-17   3.672308
609   2007-01-05   3.672632
610   2007-10-23   3.672813
611   2007-07-14   3.673000
612   2010-05-04   3.673000
613   2003-05-31   3.673000
614   2010-09-03   3.673396
615   2007-09-10   3.673750
616   2004-11-15   3.673750
617   2006-12-06   3.673846
618   2003-10-19   3.674000
619   2003-08-10   3.674167
620   2005-07-12   3.674286
621   2008-02-07   3.674444
622   2003-06-28   3.674545
623   2002-07-22   3.675000
624   2003-11-07   3.675556
625   2008-06-26   3.675909
626   2005-02-14   3.676000
627   2004-09-18   3.676250
628   2009-07-22   3.676341
629   2003-07-25   3.677143
630   2005-05-28   3.677143
631   2007-07-23   3.677333
632   2010-11-08   3.679091
633   2005-08-27   3.679286
634   2002-04-03   3.680000
635   2003-05-26   3.680000
636   2005-05-18   3.680000
637   2003-08-05   3.680000
638   2010-10-02   3.680345
639   2007-06-19   3.680769
640   2003-10-18   3.681111
641   2010-07-09   3.681250
642   2009-04-24   3.681333
643   2004-02-12   3.681333
644   2010-01-19   3.681622
645   2006-06-08   3.681875
646   2007-10-17   3.682000
647   2010-01-04   3.682642
648   2008-04-06   3.682812
649   2008-11-15   3.682813
650   2007-08-08   3.682941
651   2003-10-17   3.683333
652   2003-10-20   3.683333
653   2011-11-09   3.683766
654   2007-11-20   3.684286
655   2003-05-05   3.685000
656   2008-11-21   3.685278
657   2007-10-10   3.685500
658   2006-04-23   3.686429
659   2010-07-21   3.686863
660   2013-09-12   3.686914
661   2009-09-16   3.686944
662   2005-04-06   3.687500
663   2003-01-24   3.687692
664   2009-09-12   3.687742
665   2005-02-20   3.687778
666   2007-05-24   3.687857
667   2003-10-06   3.688333
668   2006-10-21   3.688438
669   2010-09-07   3.688451
670   2009-10-09   3.688864
671   2003-08-28   3.689000
672   2005-05-07   3.689231
673   2006-12-11   3.689500
674   2007-12-26   3.689524
675   2006-10-16   3.689545
676   2007-08-05   3.690000
677   2002-05-02   3.690000
678   2004-11-30   3.690000
679   2008-01-05   3.690435
680   2006-01-26   3.690500
681   2012-05-28   3.690575
682   2009-10-06   3.691091
683   2007-11-27   3.691250
684   2005-03-09   3.691250
685   2009-11-22   3.691333
686   2010-07-02   3.691833
687   2006-07-07   3.691875
688   2012-02-02   3.691912
689   2003-05-10   3.692000
690   2007-12-20   3.692632
691   2003-03-09   3.692727
692   2008-07-24   3.692857
693   2002-08-22   3.692857
694   2010-01-16   3.693333
695   2007-06-08   3.693333
696   2010-12-08   3.693382
697   2004-01-13   3.693750
698   2011-10-24   3.694507
699   2006-03-31   3.694615
700   2009-10-31   3.694783
701   2009-03-26   3.694783
702   2006-04-11   3.695455
703   2009-12-04   3.695625
704   2006-04-09   3.696087
705   2005-06-20   3.696364
706   2003-11-26   3.696364
707   2005-08-20   3.696667
708   2003-05-23   3.696667
709   2005-12-14   3.696923
710   2008-01-25   3.697000
711   2007-03-06   3.697333
712   2008-03-03   3.697576

In [25]:
pd.set_option('display.max_rows',None)
myAvgBeer_Review_by_YearandMonth = pd.to_datetime(myAvgBeer_Review['date']).dt.year.astype(str) + "-" + pd.to_datetime(myAvgBeer_Review['date']).dt.month.astype(str)

In [26]:
myAvgBeer_Review_by_YearandMonth.value_counts().sort_index()

date
1998-1      1
1998-10     2
1998-12     2
1998-2      4
1998-3      5
1998-4      3
1998-5      3
1998-6      1
1998-7      1
1998-8      2
1998-9      2
1999-10     2
1999-11     1
1999-12     1
1999-2      2
1999-5      1
1999-6      1
1999-7      1
2000-10     1
2000-11     1
2000-12     1
2000-2      1
2000-4      1
2000-6      1
2000-7      2
2000-9      2
2001-1      2
2001-10    19
2001-11    16
2001-12    16
2001-2      3
2001-3      4
2001-4      2
2001-6      3
2001-7      4
2001-8     10
2001-9     11
2002-1     10
2002-10    31
2002-11    30
2002-12    31
2002-2     19
2002-3     30
2002-4     29
2002-5     30
2002-6     29
2002-7     31
2002-8     31
2002-9     29
2003-1     31
2003-10    31
2003-11    30
2003-12    31
2003-2     28
2003-3     31
2003-4     29
2003-5     31
2003-6     30
2003-7     31
2003-8     31
2003-9     30
2004-1     31
2004-10    31
2004-11    30
2004-12    31
2004-2     29
2004-3     31
2004-4     30
2004-5     31
2004-6     30
2004-7     31
2004-8     31
2004-9     30
2005-1     31
2005-10    31
2005-11    30
2005-12    31
2005-2     28
2005-3     31
2005-4     30
2005-5     31
2005-6     30
2005-7     31
2005-8     31
2005-9     30
2006-1     31
2006-10    31
2006-11    30
2006-12    31
2006-2     28
2006-3     31
2006-4     30
2006-5     31
2006-6     30
2006-7     31
2006-8     31
2006-9     30
2007-1     31
2007-10    31
2007-11    30
2007-12    31
2007-2     28
2007-3     31
2007-4     30
2007-5     31
2007-6     30
2007-7     31
2007-8     31
2007-9     30
2008-1     31
2008-10    31
2008-11    30
2008-12    31
2008-2     29
2008-3     31
2008-4     30
2008-5     31
2008-6     30
2008-7     31
2008-8     31
2008-9     30
2009-1     31
2009-10    30
2009-11    30
2009-12    31
2009-2     28
2009-3     31
2009-4     30
2009-5     31
2009-6     30
2009-7     31
2009-8     31
2009-9     30
2010-1     31
2010-10    31
2010-11    30
2010-12    31
2010-2     28
2010-3     31
2010-4     30
2010-5     31
2010-6     30
2010-7     31
2010-8     31
2010-9     30
2011-1     31
2011-10    31
2011-11    30
2011-12    31
2011-2     28
2011-3     31
2011-4     30
2011-5     31
2011-6     30
2011-7     31
2011-8     31
2011-9     30
2012-1     31
2012-10    31
2012-11    30
2012-12    31
2012-2     28
2012-3     31
2012-4     30
2012-5     31
2012-6     30
2012-7     31
2012-8     31
2012-9     30
2013-1     31
2013-10    31
2013-11    30
2013-12    31
2013-2     28
2013-3     31
2013-4     30
2013-5     31
2013-6     30
2013-7     31
2013-8     31
2013-9     30
2014-1     31
2014-10    31
2014-11    30
2014-12    31
2014-2     28
2014-3     31
2014-4     30
2014-5     31
2014-6     30
2014-7     31
2014-8     31
2014-9     30
2015-1     31
2015-10    31
2015-11    30
2015-12    31
2015-2     28
2015-3     31
2015-4     30
2015-5     31
2015-6     30
2015-7     31
2015-8     31
2015-9     30
2016-1     31
2016-10    31
2016-11    30
2016-12    31
2016-2     29
2016-3     31
2016-4     30
2016-5     31
2016-6     30
2016-7     31
2016-8     31
2016-9     30
2017-1     31
2017-10    31
2017-11    30
2017-12    31
2017-2     28
2017-3     31
2017-4     30
2017-5     31
2017-6     30
2017-7     31
2017-8     31
2017-9     30
2018-1     31
2018-2     28
2018-3     31
2018-4     30
2018-5     31
2018-6     30
2018-7     31
2018-8     31
2018-9     30
Name: count, dtype: int64