In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [5]:
myAirplane_Avg = pd.read_csv("/anvil/projects/tdm/data/flights/subset/1990.csv")

In [6]:
# Step 4 - # Display first 5 rows of data from the Airplane data frame(similar to Top 5 in sql) - click run

In [7]:
myAirplane_Avg.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1990,1,3,3,1707.0,1630,1755.0,1723,US,29,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1990,1,4,4,1706.0,1630,1807.0,1723,US,29,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1990,1,5,5,1629.0,1630,1715.0,1723,US,29,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1990,1,6,6,1633.0,1630,1718.0,1723,US,29,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1990,1,8,1,1630.0,1630,1726.0,1723,US,29,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [8]:
#Set display option to show all columns - Configures Pandas to display all columns of a DataFrame when printed or 
#displayed in an interactive environment (e.g., Jupyter Notebook)

In [9]:
pd.set_option('display.max_columns',None)
#pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myAirplane_Avg

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1990,1,3,3,1707.0,1630,1755.0,1723,US,29,NaN,48.0,53,NaN,32.0,37.0,CMH,IND,182.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1990,1,4,4,1706.0,1630,1807.0,1723,US,29,NaN,61.0,53,NaN,44.0,36.0,CMH,IND,182.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1990,1,5,5,1629.0,1630,1715.0,1723,US,29,NaN,46.0,53,NaN,-8.0,-1.0,CMH,IND,182.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1990,1,6,6,1633.0,1630,1718.0,1723,US,29,NaN,45.0,53,NaN,-5.0,3.0,CMH,IND,182.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1990,1,8,1,1630.0,1630,1726.0,1723,US,29,NaN,56.0,53,NaN,3.0,0.0,CMH,IND,182.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270888,1990,12,20,4,2150.0,2128,2233.0,2220,DL,229,NaN,103.0,112,NaN,13.0,22.0,SLC,PDX,630.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5270889,1990,12,21,5,2207.0,2128,2252.0,2220,DL,229,NaN,105.0,112,NaN,32.0,39.0,SLC,PDX,630.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5270890,1990,12,22,6,2145.0,2128,2219.0,2220,DL,229,NaN,94.0,112,NaN,-1.0,17.0,SLC,PDX,630.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5270891,1990,12,23,7,2139.0,2128,2225.0,2220,DL,229,NaN,106.0,112,NaN,5.0,11.0,SLC,PDX,630.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5270892,1990,12,24,1,2128.0,2128,2212.0,2220,DL,229,NaN,104.0,112,NaN,-8.0,0.0,SLC,PDX,630.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [10]:
#Group by 'Dest' and calculate average arrival delay - Groups the myAirplane_Avg DataFrame by destination (Dest), 
#calculates the average arrival delay (ArrDelay) for each destination, and resets the index to return a clean DataFrame

In [11]:
pd.set_option('display.max_rows',None) # - pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myAirplane_Avg.groupby('Dest')['ArrDelay'].mean().reset_index(name='Avg_Delay')

    Dest  Avg_Delay
0    ABE   4.774940
1    ABQ   7.772013
2    ACY   5.588076
3    AGS   8.358385
4    ALB   7.511260
5    AMA   8.567987
6    ANC  11.361536
7    ATL   8.597035
8    ATW -11.253012
9    AUS   6.218884
10   AVL   5.561917
11   AVP   7.239102
12   AZO   3.334252
13   BDL   7.501587
14   BET  11.801754
15   BFL   5.705599
16   BGM   4.609019
17   BGR  11.619406
18   BHM   5.618216
19   BIL   4.306908
20   BIS   4.325692
21   BLI   6.571663
22   BNA   2.990541
23   BOI   7.802144
24   BOS   8.681390
25   BTM   6.111433
26   BTR   7.727585
27   BTV   7.184737
28   BUF   7.623859
29   BUR   2.977912
30   BWI   6.117801
31   BZN   6.008305
32   CAE   8.454399
33   CAK   5.693481
34   CCR   1.058360
35   CDV   8.376488
36   CHA   4.973240
37   CHO   1.202899
38   CHS   6.199248
39   CID   7.011452
40   CLE   6.613217
41   CLT   4.672193
42   CMH   6.809549
43   CMI   4.130476
44   COS   6.412706
45   CPR   2.165428
46   CRP   8.065865
47   CRW   4.073368
48   CSG   9.576809
49   CVG   6.963399
50   DAB   8.970992
51   DAL   6.657802
52   DAY   4.349131
53   DCA   4.995616
54   DEN   8.176495
55   DET   7.003241
56   DFW   7.895275
57   DLH   2.092912
58   DRO   8.512270
59   DSM   7.854620
60   DTW   4.494812
61   EFD   1.714906
62   EGE  19.767606
63   ELM   5.068319
64   ELP   7.591237
65   ERI  10.334065
66   EUG   7.310419
67   EVV   1.030660
68   EWR  10.903922
69   EYW   2.352344
70   FAI  13.715238
71   FAR   6.487277
72   FAT   6.104785
73   FAY   4.626731
74   FCA   9.362340
75   FLG   4.606115
76   FLL   7.299241
77   FNT   7.088152
78   FSD   5.740753
79   FWA   5.075323
80   GCN   5.231303
81   GEG   7.734324
82   GFK   5.158886
83   GJT   6.406498
84   GNV   6.881706
85   GPT  -2.193137
86   GRB   2.871899
87   GRR   6.038218
88   GSO   5.930502
89   GSP   5.207854
90   GST   5.843373
91   GTF   4.536173
92   GUC  12.874194
93   GUM   6.956490
94   HDN  12.991055
95   HLN   5.775599
96   HNL   8.482858
97   HOU   7.463272
98   HPN   7.098569
99   HRL   6.350517
100  HSV   5.297237
101  HTS   0.164094
102  IAD   3.775034
103  IAH   7.521459
104  ICT   5.335067
105  IDA   5.316095
106  ILM   2.909057
107  IND   6.110519
108  ISO   2.047059
109  ISP   5.632582
110  ITH   5.904255
111  JAC   6.813785
112  JAN   6.772257
113  JAX   8.032874
114  JFK   8.567413
115  JNU  10.103102
116  KOA   5.623547
117  KTN  11.180851
118  LAN   1.454231
119  LAS   6.340679
120  LAX   6.779259
121  LBB   7.384796
122  LEX   8.916368
123  LFT   1.282288
124  LGA   9.741541
125  LGB   6.552703
126  LIH   6.982906
127  LIT   9.241714
128  LNK   8.099789
129  LSE   2.272727
130  LYH   1.934211
131  MAF   6.150701
132  MBS   5.262454
133  MCI   6.683866
134  MCO   7.436247
135  MDT   6.134694
136  MDW   6.148504
137  MEM   1.680644
138  MFE   6.357101
139  MFR   5.997268
140  MGM   8.027061
141  MHT   7.717308
142  MIA   4.637924
143  MKC        NaN
144  MKE   5.675064
145  MLB   7.236101
146  MLI   6.687482
147  MLU  11.687854
148  MOB   6.812799
149  MOT   0.822211
150  MRY   4.212573
151  MSN   5.260940
152  MSO   5.265374
153  MSP   4.161600
154  MSY   6.962229
155  MYR   2.934494
156  OAJ   3.487007
157  OAK   4.159836
158  OGG   5.294616
159  OKC   8.151771
160  OMA   6.698528
161  OME   9.191268
162  ONT   6.904306
163  ORD   7.279122
164  ORF   5.774474
165  ORH   5.244295
166  OTZ  10.460819
167  PBI   7.941035
168  PDX   6.506988
169  PHF   4.002979
170  PHL   9.451961
171  PHX   6.952283
172  PIA   5.703983
173  PIT   6.397241
174  PMD  -1.022398
175  PNS   5.301025
176  PSC   8.784916
177  PSE  30.533333
178  PSG  10.740496
179  PSP   5.731365
180  PUB   1.265643
181  PVD   6.601589
182  PWM   9.114453
183  RAP   4.070611
184  RDM  23.883929
185  RDU   2.724541
186  RIC   5.670268
187  RNO   7.144272
188  ROA   4.295752
189  ROC   7.981662
190  ROP   6.254630
191  ROR  14.118687
192  RST   5.783036
193  RSW   7.926745
194  SAN   7.583277
195  SAT   6.979337
196  SAV   6.684960
197  SBA   5.758758
198  SBN   3.156008
199  SCC  14.648810
200  SCK   0.287529
201  SDF   6.256240
202  SEA   9.449260
203  SFO   8.622028
204  SGF   7.448867
205  SHV   8.425185
206  SIT  10.040785
207  SJC   3.955744
208  SJU   5.789307
209  SLC   6.363491
210  SMF   6.566626
211  SNA   5.362499
212  SPN   5.706017
213  SRQ   7.596901
214  STL   4.880907
215  STT   3.573432
216  STX   4.188554
217  SUN  22.815789
218  SUX   6.719050
219  SWF  10.140813
220  SYR   6.829898
221  TLH   3.851421
222  TOL   7.042154
223  TPA   6.700325
224  TRI   3.468801
225  TUL   8.025631
226  TUS   9.059098
227  TVC   6.966601
228  TVL   1.272615
229  TYS   6.538309
230  UCA   1.568915
231  VPS   1.171456
232  WRG   8.794408
233  YAK   7.709576
234  YAP  23.293233
235  YUM   3.883364